# Generated by Django 5.1.3 on 2024-11-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSN', models.CharField(max_length=9)),
                ('QR_code', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('mutuelle', models.CharField(max_length=50)),
                ('medecin_traitant', models.CharField(max_length=50)),
                ('personne_contact', models.CharField(max_length=50)),
            ],
        ),
    ]
