# Generated by Django 5.1.4 on 2024-12-18 21:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiologicalExam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=100)),
                ('result', models.TextField()),
                ('has_graph', models.BooleanField(default=False)),
                ('exam_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consultation_summary', models.TextField()),
                ('examination_required', models.TextField()),
                ('hospital', models.TextField()),
                ('consultation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('speciality', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Dpi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('social_security_number', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('emergency_contact_relationship', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('blood_type', models.CharField(max_length=3)),
                ('mutuelle_name', models.CharField(max_length=255)),
                ('mutuelle_policy_number', models.CharField(max_length=100)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('hospital', models.TextField()),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Pharmacist', 'Pharmacist'), ('LabTechnician', 'Lab Technician'), ('Radiologist', 'Radiologist'), ('SuperAdmin', 'Super Admin'), ('Admin', 'Admin')], max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BiologicalExamParam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('param_name', models.CharField(max_length=100)),
                ('before_treatment_value', models.FloatField()),
                ('after_treatment_value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('biological_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi_app.biologicalexam')),
            ],
        ),
        migrations.AddField(
            model_name='biologicalexam',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi_app.consultation'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='dpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi_app.dpi'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('validated', models.BooleanField(default=False)),
                ('prescription_date', models.DateField(default=django.utils.timezone.now)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi_app.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi_app.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='RadiologicalExam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.TextField()),
                ('image_url', models.TextField()),
                ('result', models.TextField()),
                ('exam_date', models.DateField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi_app.consultation')),
                ('radiologist', models.ForeignKey(limit_choices_to={'role': 'Radiologist'}, on_delete=django.db.models.deletion.CASCADE, to='dpi_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='NursingRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('care_name', models.TextField()),
                ('patient_observation', models.TextField()),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi_app.consultation')),
                ('nurse', models.ForeignKey(limit_choices_to={'role': 'Nurse'}, on_delete=django.db.models.deletion.CASCADE, to='dpi_app.staff')),
            ],
        ),
        migrations.AddField(
            model_name='dpi',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpi_app.staff'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, to='dpi_app.staff'),
        ),
        migrations.AddField(
            model_name='biologicalexam',
            name='lab_technician',
            field=models.ForeignKey(limit_choices_to={'role': 'LabTechnician'}, on_delete=django.db.models.deletion.CASCADE, to='dpi_app.staff'),
        ),
    ]
