# Generated by Django 5.1.4 on 2024-12-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='speciality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
