# Generated by Django 5.1.4 on 2024-12-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nursingrecord',
            name='dpi',
        ),
        migrations.AddField(
            model_name='consultation',
            name='hospital',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dpi',
            name='hospital',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
