# Generated by Django 5.1.4 on 2024-12-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi_app', '0002_staff_speciality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.AlterField(
            model_name='dpi',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
