# Generated by Django 5.1.4 on 2024-12-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi_app', '0002_remove_nursingrecord_dpi_consultation_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Nurse', 'Nurse'), ('Pharmacist', 'Pharmacist'), ('LabTechnician', 'Lab Technician'), ('Radiologist', 'Radiologist'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
