# Generated by Django 5.1.4 on 2024-12-24 18:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi_app', '0003_delete_doctor_alter_dpi_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biologicalexamparam',
            old_name='after_treatment_value',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='biologicalexam',
            name='has_graph',
        ),
        migrations.RemoveField(
            model_name='biologicalexamparam',
            name='before_treatment_value',
        ),
        migrations.RemoveField(
            model_name='radiologicalexam',
            name='image_url',
        ),
        migrations.AddField(
            model_name='radiologicalexam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='radiological_exam_images/'),
        ),
        migrations.AlterField(
            model_name='biologicalexam',
            name='exam_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 24, 18, 28, 12, 279645, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='biologicalexam',
            name='lab_technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi_app.staff'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi_app.staff'),
        ),
        migrations.AlterField(
            model_name='nursingrecord',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi_app.staff'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 24, 18, 28, 12, 278583, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='radiologicalexam',
            name='exam_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 24, 18, 28, 12, 280823, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='radiologicalexam',
            name='radiologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi_app.staff'),
        ),
    ]
