# Generated by Django 5.1.4 on 2024-12-26 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi_app', '0004_rename_after_treatment_value_biologicalexamparam_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biologicalexamparam',
            name='unit',
        ),
        migrations.AlterField(
            model_name='biologicalexam',
            name='lab_technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dpi_app.staff'),
        ),
        migrations.AlterField(
            model_name='biologicalexam',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biologicalexamparam',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nursingrecord',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dpi_app.staff'),
        ),
        migrations.AlterField(
            model_name='nursingrecord',
            name='patient_observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radiologicalexam',
            name='radiologist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dpi_app.staff'),
        ),
        migrations.AlterField(
            model_name='radiologicalexam',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
