# Generated by Django 5.1.4 on 2024-12-25 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi_app', '0004_rename_after_treatment_value_biologicalexamparam_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalexam',
            name='exam_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='radiologicalexam',
            name='exam_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
