# Generated by Django 5.1.4 on 2024-12-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi_app', '0005_remove_biologicalexamparam_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpi',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
