# Generated by Django 5.1.4 on 2024-12-25 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi_app', '0005_alter_biologicalexam_exam_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_date',
            field=models.DateField(default=datetime.date(2024, 12, 25)),
        ),
    ]
