# Generated by Django 5.1.4 on 2024-12-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi_app', '0005_remove_biologicalexamparam_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalexam',
            name='exam_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='nursingrecord',
            name='record_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='radiologicalexam',
            name='exam_date',
            field=models.DateField(null=True),
        ),
    ]
