# Generated by Django 5.1.4 on 2024-12-25 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi_app', '0006_alter_prescription_prescription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
