# Generated by Django 5.1.4 on 2024-12-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi_app', '0006_dpi_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
