# Generated by Django 5.1.4 on 2024-12-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpi_app', '0007_alter_dpi_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='examination_required',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='hospital',
        ),
    ]
