# Generated by Django 5.1.4 on 2025-01-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpi_app', '0006_alter_biologicalexam_exam_date_and_more'),
        ('dpi_app', '0008_remove_consultation_examination_required_and_more'),
    ]

    operations = [
    ]
