# Generated by Django 5.1.4 on 2025-01-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi_app', '0009_merge_20250102_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='social_security_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
