# Generated by Django 5.1.4 on 2025-01-03 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi_app', '0010_alter_dpi_social_security_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='consultation',
        ),
        migrations.AddField(
            model_name='consultation',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpi_app.prescription'),
        ),
    ]
