# Generated by Django 5.1.4 on 2025-01-05 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi_app', '0011_remove_prescription_consultation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='email',
            field=models.EmailField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dpi',
            name='social_security_number',
            field=models.CharField(db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='dpi_app.prescription'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(db_index=True, max_length=100),
        ),
    ]
